package ru.murad.yourmarket.model.enums;

public enum AdvertisementStatus {
    DRAFT, WAITING_FOR_PAYMENT, PAID, WAITING_FOR_MODERATION, PUBLISHED, DELETED,
    PUBLICATION_IN_PROGRESS, PUBLICATION_RECONCILIATION_REQUIRED,
    PUBLICATION_FAILED, REJECTED, EXPIRATION_IN_PROGRESS, EXPIRED
}
