package ru.murad.yourmarket.model.enums;

public enum AdvertisementCreationStep {
    NONE, WAITING_FOR_CATEGORY, WAITING_FOR_TITLE, WAITING_FOR_DESCRIPTION,
    WAITING_FOR_PRICE, WAITING_FOR_PHOTO, WAITING_FOR_CITY,
    WAITING_FOR_CONTACT_CHOICE, WAITING_FOR_CUSTOM_CONTACT, PREVIEW
}
