package ru.murad.yourmarket.model.enums;

public enum AdvertisementCreationStep {
    NONE, WAITING_FOR_CATEGORY, WAITING_FOR_VEHICLE_BRAND, WAITING_FOR_VEHICLE_BRAND_SEARCH, WAITING_FOR_CUSTOM_VEHICLE_BRAND,
    WAITING_FOR_VEHICLE_MODEL, WAITING_FOR_VEHICLE_MODEL_SEARCH, WAITING_FOR_CUSTOM_VEHICLE_MODEL, WAITING_FOR_VEHICLE_YEAR,
    WAITING_FOR_VEHICLE_TRANSMISSION, WAITING_FOR_VEHICLE_ENGINE_TYPE, WAITING_FOR_VEHICLE_ENGINE_VOLUME,
    WAITING_FOR_VEHICLE_MILEAGE, WAITING_FOR_VEHICLE_DRIVE_TYPE, WAITING_FOR_TITLE, WAITING_FOR_DESCRIPTION,
    WAITING_FOR_PRICE, WAITING_FOR_PHOTO, WAITING_FOR_REGION, WAITING_FOR_REGION_SEARCH,
    WAITING_FOR_CITY, WAITING_FOR_CITY_SEARCH, WAITING_FOR_CUSTOM_LOCALITY,
    WAITING_FOR_CONTACT_CHOICE, WAITING_FOR_CUSTOM_CONTACT, PREVIEW
}
