package ru.murad.yourmarket.service.impl;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import ru.murad.yourmarket.exception.*; import ru.murad.yourmarket.model.AdvertisementDraft; import ru.murad.yourmarket.model.enums.AdvertisementCreationStep; import ru.murad.yourmarket.repository.AdvertisementDraftRepository; import ru.murad.yourmarket.service.*;
@Service @RequiredArgsConstructor @Transactional public class AdvertisementLocationFlowServiceImpl implements AdvertisementLocationFlowService {
 private final AdvertisementDraftRepository drafts; private final LocationCatalog catalog; private final LocationFormatter formatter;
 public AdvertisementDraft beginRegionSearch(Long id){return step(id,AdvertisementCreationStep.WAITING_FOR_REGION,AdvertisementCreationStep.WAITING_FOR_REGION_SEARCH);}
 public AdvertisementDraft chooseRegion(Long id,String code){AdvertisementDraft d=require(id); if(d.getStep()!=AdvertisementCreationStep.WAITING_FOR_REGION&&d.getStep()!=AdvertisementCreationStep.WAITING_FOR_REGION_SEARCH)throw stale(); LocationCatalog.Region r=catalog.region(code).orElseThrow(()->new DraftValidationException("Неизвестный регион.")); d.setRegionCode(r.code());d.setRegionNameSnapshot(r.name());clearCity(d); if(r.federalCity()&&r.cities().size()==1){setCity(d,r.cities().get(0));d.setStep(AdvertisementCreationStep.WAITING_FOR_CONTACT_CHOICE);}else d.setStep(AdvertisementCreationStep.WAITING_FOR_CITY);return drafts.save(d);}
 public AdvertisementDraft beginCitySearch(Long id){return step(id,AdvertisementCreationStep.WAITING_FOR_CITY,AdvertisementCreationStep.WAITING_FOR_CITY_SEARCH);}
 public AdvertisementDraft chooseCity(Long id,String code){AdvertisementDraft d=require(id);if(d.getStep()!=AdvertisementCreationStep.WAITING_FOR_CITY&&d.getStep()!=AdvertisementCreationStep.WAITING_FOR_CITY_SEARCH)throw stale();LocationCatalog.City c=catalog.cities(d.getRegionCode()).stream().filter(v->v.code().equals(code)).findFirst().orElseThrow(()->new DraftValidationException("Неизвестный город выбранного региона."));setCity(d,c);d.setStep(AdvertisementCreationStep.WAITING_FOR_CONTACT_CHOICE);return drafts.save(d);}
 public AdvertisementDraft beginCustomLocality(Long id){return step(id,AdvertisementCreationStep.WAITING_FOR_CITY,AdvertisementCreationStep.WAITING_FOR_CUSTOM_LOCALITY);}
 public AdvertisementDraft setCustomLocality(Long id,String locality){AdvertisementDraft d=require(id);if(d.getStep()!=AdvertisementCreationStep.WAITING_FOR_CUSTOM_LOCALITY)throw stale();String x=locality==null?"":locality.trim();if(!x.matches("[\\p{L}0-9 .,'-]{2,100}"))throw new DraftValidationException("Название населённого пункта содержит недопустимые символы или имеет неверную длину.");d.setCityCode("OTHER");d.setCityNameSnapshot(null);d.setCustomLocality(x);d.setCity(formatter.format(d));d.setStep(AdvertisementCreationStep.WAITING_FOR_CONTACT_CHOICE);return drafts.save(d);}
 public AdvertisementDraft backToRegions(Long id){AdvertisementDraft d=require(id);if(d.getStep()==AdvertisementCreationStep.WAITING_FOR_REGION)return d;if(d.getStep()!=AdvertisementCreationStep.WAITING_FOR_CITY&&d.getStep()!=AdvertisementCreationStep.WAITING_FOR_CITY_SEARCH&&d.getStep()!=AdvertisementCreationStep.WAITING_FOR_CUSTOM_LOCALITY)throw stale();clearCity(d);d.setStep(AdvertisementCreationStep.WAITING_FOR_REGION);return drafts.save(d);}
 private AdvertisementDraft step(Long id,AdvertisementCreationStep from,AdvertisementCreationStep to){AdvertisementDraft d=require(id);if(d.getStep()==to)return d;if(d.getStep()!=from)throw stale();d.setStep(to);return drafts.save(d);} private AdvertisementDraft require(Long id){return drafts.findByTelegramUserId(id).orElseThrow(()->new InvalidAdvertisementStateException("Активный черновик не найден."));} private RuntimeException stale(){return new InvalidAdvertisementStateException("Этот шаг уже завершён. Продолжите заполнение объявления ниже.");} private void clearCity(AdvertisementDraft d){d.setCity(null);d.setCityCode(null);d.setCityNameSnapshot(null);d.setCustomLocality(null);} private void setCity(AdvertisementDraft d,LocationCatalog.City c){d.setCityCode(c.code());d.setCityNameSnapshot(c.name());d.setCustomLocality(null);d.setCity(formatter.format(d));}
}
