package ru.murad.yourmarket.service.impl;
import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import ru.murad.yourmarket.config.PublicationProperties;import ru.murad.yourmarket.dto.response.AdvertisementResponseDto;import ru.murad.yourmarket.exception.*;import ru.murad.yourmarket.mapper.AdvertisementMapper;import ru.murad.yourmarket.model.Advertisement;import ru.murad.yourmarket.model.enums.*;import ru.murad.yourmarket.repository.*;import ru.murad.yourmarket.service.AdvertisementLifecycleTransactionService;import java.time.Instant;import java.util.*;
@Service @RequiredArgsConstructor public class AdvertisementLifecycleTransactionServiceImpl implements AdvertisementLifecycleTransactionService {private final AdvertisementRepository repository;private final AdvertisementChannelMessageRepository messages;private final AdvertisementMapper mapper;private final PublicationProperties properties;
@Override @Transactional public Advertisement authorizeDeletion(UUID id,Long user){Advertisement ad=lock(id);if(!ad.getTelegramUserId().equals(user))throw new AdvertisementNotFoundException();if(ad.getStatus()!=AdvertisementStatus.PUBLISHED&&ad.getStatus()!=AdvertisementStatus.DELETED)throw new InvalidAdvertisementStateException("Снять можно только опубликованное объявление");return ad;}
@Override @Transactional public ExpirationClaim claimExpiration(UUID id){Advertisement ad=repository.findByIdForUpdate(id).orElse(null);if(ad==null||ad.getStatus()!=AdvertisementStatus.PUBLISHED||ad.getExpiresAt()==null||ad.getExpiresAt().isAfter(Instant.now())||ad.getExpirationOperationId()!=null)return null;UUID op=UUID.randomUUID();ad.setStatus(AdvertisementStatus.EXPIRATION_IN_PROGRESS);ad.setExpirationOperationId(op);ad.setExpirationStartedAt(Instant.now());repository.save(ad);return new ExpirationClaim(ad,op);}
@Override @Transactional public AdvertisementResponseDto finishDeletion(UUID id){Advertisement ad=lock(id);if(ad.getStatus()!=AdvertisementStatus.DELETED){ad.setStatus(AdvertisementStatus.DELETED);ad.setDeletedAt(Instant.now());}return mapper.toResponse(ad);}
@Override @Transactional public Advertisement finishExpiration(UUID id,UUID op){Advertisement ad=lock(id);if(ad.getStatus()!=AdvertisementStatus.EXPIRATION_IN_PROGRESS||!Objects.equals(op,ad.getExpirationOperationId())||messages.countByAdvertisementIdAndDeletionStatusNot(id,ChannelMessageStatus.DELETED)>0)return null;ad.setStatus(AdvertisementStatus.EXPIRED);ad.setExpiredAt(Instant.now());clear(ad);return ad;}
@Override @Transactional public void releaseExpiration(UUID id,UUID op){Advertisement ad=lock(id);if(ad.getStatus()!=AdvertisementStatus.EXPIRATION_IN_PROGRESS||!Objects.equals(op,ad.getExpirationOperationId())||hasAmbiguousDelete(id))return;ad.setStatus(AdvertisementStatus.PUBLISHED);clear(ad);}
@Override @Transactional public boolean recoverStaleExpiration(UUID id){Advertisement ad=lock(id);if(ad.getStatus()!=AdvertisementStatus.EXPIRATION_IN_PROGRESS||ad.getExpirationStartedAt()==null||ad.getExpirationStartedAt().isAfter(Instant.now().minusSeconds(properties.getExpirationClaimTimeoutSeconds()))||hasAmbiguousDelete(id))return false;ad.setStatus(AdvertisementStatus.PUBLISHED);clear(ad);return true;}
private boolean hasAmbiguousDelete(UUID id){return messages.existsByAdvertisementIdAndDeletionStatus(id,ChannelMessageStatus.DELETE_IN_PROGRESS)||messages.existsByAdvertisementIdAndDeletionStatus(id,ChannelMessageStatus.DELETE_RECONCILIATION_REQUIRED);}private void clear(Advertisement ad){ad.setExpirationOperationId(null);ad.setExpirationStartedAt(null);}private Advertisement lock(UUID id){return repository.findByIdForUpdate(id).orElseThrow(AdvertisementNotFoundException::new);}}
