package ru.murad.yourmarket.service.impl;
import lombok.RequiredArgsConstructor;import lombok.extern.slf4j.Slf4j;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import ru.murad.yourmarket.config.PublicationProperties;import ru.murad.yourmarket.dto.response.AdvertisementResponseDto;import ru.murad.yourmarket.exception.*;import ru.murad.yourmarket.mapper.AdvertisementMapper;import ru.murad.yourmarket.model.*;import ru.murad.yourmarket.model.enums.*;import ru.murad.yourmarket.repository.*;import ru.murad.yourmarket.service.PublicationTransactionService;
import java.time.*;import java.util.*;
@Slf4j @Service @RequiredArgsConstructor public class PublicationTransactionServiceImpl implements PublicationTransactionService {
 private final AdvertisementRepository advertisements;private final PaymentRepository payments;private final AdvertisementChannelMessageRepository messages;private final AdvertisementMapper mapper;private final PublicationProperties properties;
 @Override @Transactional public Claim claim(UUID id,boolean fromModeration){Advertisement ad=lock(id);if(ad.getStatus()==AdvertisementStatus.PUBLISHED)return new Claim(ad,null,false,mapper.toResponse(ad));if(ad.getStatus()==AdvertisementStatus.PUBLICATION_IN_PROGRESS&&ad.getPublicationPhase()==PublicationPhase.CLAIMED&&stale(ad)){ad.setStatus(AdvertisementStatus.PUBLICATION_FAILED);clear(ad);}if(ad.getStatus()==AdvertisementStatus.PUBLICATION_IN_PROGRESS||ad.getStatus()==AdvertisementStatus.PUBLICATION_RECONCILIATION_REQUIRED)return new Claim(ad,ad.getPublicationOperationId(),false,mapper.toResponse(ad));boolean allowed=ad.getStatus()==AdvertisementStatus.PAID||ad.getStatus()==AdvertisementStatus.PUBLICATION_FAILED||(fromModeration&&ad.getStatus()==AdvertisementStatus.WAITING_FOR_MODERATION);if(!allowed)throw new InvalidAdvertisementStateException("Объявление не готово к публикации");succeededPayment(id);UUID op=UUID.randomUUID();ad.setStatus(AdvertisementStatus.PUBLICATION_IN_PROGRESS);ad.setPublicationOperationId(op);ad.setPublicationStartedAt(Instant.now());ad.setPublicationUpdatedAt(Instant.now());ad.setPublicationPhase(PublicationPhase.CLAIMED);ad.setPublicationFailureReason(null);return new Claim(advertisements.save(ad),op,true,null);}
 @Override @Transactional public void markTelegramCallStarted(UUID id,UUID op){Advertisement ad=operation(id,op);ad.setPublicationPhase(PublicationPhase.TELEGRAM_CALL_STARTED);ad.setPublicationUpdatedAt(Instant.now());}
 @Override @Transactional public void saveProgress(UUID id,UUID op,List<Integer> ids,TelegramMessageType type,boolean finalResult){Advertisement ad=operation(id,op);int start=messages.findByAdvertisementIdOrderByPosition(id).size();List<AdvertisementChannelMessage> rows=new ArrayList<>();for(int i=0;i<ids.size();i++)rows.add(AdvertisementChannelMessage.builder().advertisementId(id).publicationOperationId(op).channelMessageId(ids.get(i)).position(start+i).messageType(type).deletionStatus(ChannelMessageStatus.ACTIVE).build());messages.saveAllAndFlush(rows);ad.setPublicationPhase(finalResult?PublicationPhase.RESULT_RECEIVED:PublicationPhase.RESULT_PARTIALLY_RECEIVED);ad.setPublicationUpdatedAt(Instant.now());}
 @Override @Transactional public AdvertisementResponseDto complete(UUID id,UUID op){Advertisement ad=operation(id,op);List<AdvertisementChannelMessage> rows=messages.findByAdvertisementIdOrderByPosition(id);if(rows.isEmpty())throw new InvalidAdvertisementStateException("Нет сохранённого Telegram progress");Instant now=Instant.now();ad.setChannelMessageId(rows.get(0).getChannelMessageId());ad.setPublishedAt(now);ad.setExpiresAt(now.plus(Duration.ofDays(properties.getLifetimeDays())));ad.setStatus(AdvertisementStatus.PUBLISHED);clear(ad);return mapper.toResponse(advertisements.save(ad));}
 @Override @Transactional public void fail(UUID id,UUID op,String reason){Advertisement ad=operation(id,op);if(!messages.findByAdvertisementIdOrderByPosition(id).isEmpty())throw new InvalidAdvertisementStateException("Нельзя сбросить публикацию с progress");ad.setStatus(AdvertisementStatus.PUBLICATION_FAILED);ad.setPublicationFailureReason(safe(reason));clear(ad);}
 @Override @Transactional public void reconciliationRequired(UUID id,UUID op,String reason){Advertisement ad=operation(id,op);ad.setStatus(AdvertisementStatus.PUBLICATION_RECONCILIATION_REQUIRED);ad.setPublicationPhase(PublicationPhase.RECONCILIATION_REQUIRED);ad.setPublicationUpdatedAt(Instant.now());ad.setPublicationFailureReason(safe(reason));}
 @Override @Transactional public AdvertisementResponseDto resolve(UUID id,Resolution resolution,Integer verifiedId){Advertisement ad=lock(id);if(ad.getStatus()!=AdvertisementStatus.PUBLICATION_RECONCILIATION_REQUIRED)throw new InvalidAdvertisementStateException("Reconciliation не требуется");succeededPayment(id);UUID oldOp=ad.getPublicationOperationId();List<AdvertisementChannelMessage> rows=messages.findByAdvertisementIdOrderByPosition(id);if(resolution==Resolution.RETRY_AFTER_VERIFICATION){if(!rows.isEmpty()||ad.getChannelMessageId()!=null)throw new InvalidAdvertisementStateException("Сохранён Telegram progress");ad.setStatus(AdvertisementStatus.PUBLICATION_FAILED);clear(ad);}else{if(verifiedId==null||verifiedId<=0)throw new InvalidAdvertisementStateException("channelMessageId должен быть положительным");if(rows.stream().anyMatch(m->!m.getChannelMessageId().equals(verifiedId))&&!rows.isEmpty())throw new InvalidAdvertisementStateException("channelMessageId конфликтует с progress");if(rows.isEmpty())messages.saveAndFlush(AdvertisementChannelMessage.builder().advertisementId(id).publicationOperationId(oldOp).channelMessageId(verifiedId).position(0).messageType(TelegramMessageType.PHOTO).deletionStatus(ChannelMessageStatus.ACTIVE).build());Instant published=ad.getPublishedAt()==null?Instant.now():ad.getPublishedAt();ad.setChannelMessageId(verifiedId);ad.setPublishedAt(published);ad.setExpiresAt(published.plus(Duration.ofDays(properties.getLifetimeDays())));ad.setStatus(AdvertisementStatus.PUBLISHED);clear(ad);}log.info("Publication reconciliation advertisementId={}, action={}, operationId={}",id,resolution,oldOp);return mapper.toResponse(advertisements.save(ad));}
 @Override @Transactional public void recoverStale(UUID id){Advertisement ad=lock(id);if(ad.getStatus()!=AdvertisementStatus.PUBLICATION_IN_PROGRESS||!stale(ad))return;if(ad.getPublicationPhase()==PublicationPhase.CLAIMED&&messages.findByAdvertisementIdOrderByPosition(id).isEmpty()){ad.setStatus(AdvertisementStatus.PUBLICATION_FAILED);clear(ad);}else{ad.setStatus(AdvertisementStatus.PUBLICATION_RECONCILIATION_REQUIRED);ad.setPublicationPhase(PublicationPhase.RECONCILIATION_REQUIRED);ad.setPublicationUpdatedAt(Instant.now());}}
 private void succeededPayment(UUID id){Payment p=payments.findByAdvertisementId(id).orElseThrow(PaymentNotFoundException::new);if(p.getStatus()!=PaymentStatus.SUCCEEDED)throw new InvalidPaymentStateException("Платёж не подтверждён");}
 private Advertisement lock(UUID id){return advertisements.findByIdForUpdate(id).orElseThrow(AdvertisementNotFoundException::new);}
 private Advertisement operation(UUID id,UUID op){Advertisement ad=lock(id);if(ad.getStatus()!=AdvertisementStatus.PUBLICATION_IN_PROGRESS||!Objects.equals(op,ad.getPublicationOperationId()))throw new InvalidAdvertisementStateException("Попытка публикации уже завершена");return ad;}
 private boolean stale(Advertisement ad){return ad.getPublicationUpdatedAt()!=null&&ad.getPublicationUpdatedAt().isBefore(Instant.now().minusSeconds(120));}
 private void clear(Advertisement ad){ad.setPublicationOperationId(null);ad.setPublicationStartedAt(null);ad.setPublicationUpdatedAt(null);ad.setPublicationPhase(null);}
 private String safe(String s){return s==null?"Telegram error":s.substring(0,Math.min(500,s.length()));}
}
