package ru.murad.yourmarket.service;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*; import java.util.*; import org.junit.jupiter.api.*; import ru.murad.yourmarket.model.AdvertisementDraft; import ru.murad.yourmarket.model.enums.*; import ru.murad.yourmarket.repository.AdvertisementDraftRepository; import ru.murad.yourmarket.service.impl.AdvertisementLocationFlowServiceImpl;
class AdvertisementLocationFlowServiceTest { AdvertisementDraftRepository drafts=mock(AdvertisementDraftRepository.class); AdvertisementDraft draft; AdvertisementLocationFlowService flow;
 @BeforeEach void setup(){LocationCatalog c=new LocationCatalog();c.load();draft=AdvertisementDraft.builder().telegramUserId(1L).chatId(1L).step(AdvertisementCreationStep.WAITING_FOR_REGION).build();when(drafts.findByTelegramUserId(1L)).thenReturn(Optional.of(draft));when(drafts.save(any())).thenAnswer(i->i.getArgument(0));flow=new AdvertisementLocationFlowServiceImpl(drafts,c,new LocationFormatter());}
 @Test void choosingRegionClearsOldCityAndShowsCities(){draft.setCityCode("OLD");draft.setCityNameSnapshot("Old");flow.chooseRegion(1L,"DAGESTAN");assertEquals("DAGESTAN",draft.getRegionCode());assertNull(draft.getCityCode());assertEquals(AdvertisementCreationStep.WAITING_FOR_CITY,draft.getStep());}
 @Test void catalogCityStoresSnapshots(){flow.chooseRegion(1L,"DAGESTAN");flow.chooseCity(1L,"MAKHACHKALA");assertEquals("Махачкала",draft.getCityNameSnapshot());assertEquals("Республика Дагестан, Махачкала",draft.getCity());assertEquals(AdvertisementCreationStep.WAITING_FOR_CONTACT_CHOICE,draft.getStep());}
 @Test void customLocalityIsStructuredAndValidated(){flow.chooseRegion(1L,"DAGESTAN");flow.beginCustomLocality(1L);flow.setCustomLocality(1L,"село Хучни");assertEquals("OTHER",draft.getCityCode());assertEquals("село Хучни",draft.getCustomLocality());assertThrows(RuntimeException.class,()->flow.setCustomLocality(1L,"<script>"));}
 @Test void federalCitySkipsRepeatedCitySelection(){flow.chooseRegion(1L,"MOSCOW");assertEquals(AdvertisementCreationStep.WAITING_FOR_CONTACT_CHOICE,draft.getStep());assertEquals("Москва",draft.getCity());}
 @Test void backToRegionsClearsCity(){flow.chooseRegion(1L,"DAGESTAN");flow.chooseCity(1L,"DERBENT");draft.setStep(AdvertisementCreationStep.WAITING_FOR_CITY);flow.backToRegions(1L);assertNull(draft.getCityCode());assertEquals(AdvertisementCreationStep.WAITING_FOR_REGION,draft.getStep());}
}
