package ru.murad.yourmarket.service;
import org.junit.jupiter.api.Test;import ru.murad.yourmarket.config.PublicationProperties;import ru.murad.yourmarket.mapper.AdvertisementMapper;import ru.murad.yourmarket.model.Advertisement;import ru.murad.yourmarket.model.enums.*;import ru.murad.yourmarket.repository.*;import ru.murad.yourmarket.service.impl.AdvertisementLifecycleTransactionServiceImpl;import java.time.Instant;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class AdvertisementExpirationTransactionServiceTest {AdvertisementRepository ads=mock(AdvertisementRepository.class);AdvertisementChannelMessageRepository messages=mock(AdvertisementChannelMessageRepository.class);PublicationProperties properties=new PublicationProperties();AdvertisementLifecycleTransactionServiceImpl service=new AdvertisementLifecycleTransactionServiceImpl(ads,messages,mock(AdvertisementMapper.class),properties);UUID id=UUID.randomUUID();
@Test void expiredPublishedAdvertisementGetsOwnedClaim(){Advertisement ad=ad(AdvertisementStatus.PUBLISHED);when(ads.findByIdForUpdate(id)).thenReturn(Optional.of(ad));var claim=service.claimExpiration(id);assertNotNull(claim);assertEquals(AdvertisementStatus.EXPIRATION_IN_PROGRESS,ad.getStatus());assertEquals(claim.operationId(),ad.getExpirationOperationId());}
@Test void futureAdvertisementCannotBeClaimed(){Advertisement ad=ad(AdvertisementStatus.PUBLISHED);ad.setExpiresAt(Instant.now().plusSeconds(30));when(ads.findByIdForUpdate(id)).thenReturn(Optional.of(ad));assertNull(service.claimExpiration(id));}
@Test void oldOwnerCannotFinishNewClaim(){Advertisement ad=ad(AdvertisementStatus.EXPIRATION_IN_PROGRESS);UUID current=UUID.randomUUID();ad.setExpirationOperationId(current);when(ads.findByIdForUpdate(id)).thenReturn(Optional.of(ad));assertNull(service.finishExpiration(id,UUID.randomUUID()));assertEquals(AdvertisementStatus.EXPIRATION_IN_PROGRESS,ad.getStatus());assertNotNull(service.finishExpiration(id,current));assertEquals(AdvertisementStatus.EXPIRED,ad.getStatus());}
@Test void remainingMessagePreventsFinish(){Advertisement ad=ad(AdvertisementStatus.EXPIRATION_IN_PROGRESS);UUID op=UUID.randomUUID();ad.setExpirationOperationId(op);when(ads.findByIdForUpdate(id)).thenReturn(Optional.of(ad));when(messages.countByAdvertisementIdAndDeletionStatusNot(id,ChannelMessageStatus.DELETED)).thenReturn(1L);assertNull(service.finishExpiration(id,op));assertEquals(AdvertisementStatus.EXPIRATION_IN_PROGRESS,ad.getStatus());}
@Test void staleSafeClaimReturnsToPublished(){Advertisement ad=ad(AdvertisementStatus.EXPIRATION_IN_PROGRESS);ad.setExpirationOperationId(UUID.randomUUID());ad.setExpirationStartedAt(Instant.now().minusSeconds(700));when(ads.findByIdForUpdate(id)).thenReturn(Optional.of(ad));assertTrue(service.recoverStaleExpiration(id));assertEquals(AdvertisementStatus.PUBLISHED,ad.getStatus());assertNull(ad.getExpirationOperationId());}
@Test void reconciliationDeletePreventsRecovery(){Advertisement ad=ad(AdvertisementStatus.EXPIRATION_IN_PROGRESS);ad.setExpirationOperationId(UUID.randomUUID());ad.setExpirationStartedAt(Instant.now().minusSeconds(700));when(ads.findByIdForUpdate(id)).thenReturn(Optional.of(ad));when(messages.existsByAdvertisementIdAndDeletionStatus(id,ChannelMessageStatus.DELETE_RECONCILIATION_REQUIRED)).thenReturn(true);assertFalse(service.recoverStaleExpiration(id));assertEquals(AdvertisementStatus.EXPIRATION_IN_PROGRESS,ad.getStatus());}
private Advertisement ad(AdvertisementStatus status){return Advertisement.builder().id(id).status(status).expiresAt(Instant.now().minusSeconds(1)).build();}}
